# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2e6c4ef138e93bc94ab5a735f1619d4075417c2a932495ffcc396385fd21dc1639420d0eb478059177e0565adf18de2953a1a29b1e48e2f709dba317900883

test:
  secret_key_base: e3cab3a7704940301b5c79ae3418d66c0ca231b156c27d562d9b46462007dee5161846bb7e298457f7b1dadd50580ff1da1771879df71557e810274d4f965ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
